/*
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetProvider'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetProvider', 'Returns provider details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetProviders'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetProviders', 'Returns list of provider details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetPatient'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetPatient', 'Returns patient details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetUpdatedPatients'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetUpdatedPatients', 'Returns list of patient detials', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/FindPatient'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/FindPatient', 'Returns patient details. Can create patient if not found', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/CalculatePatientBatches'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/CalculatePatientBatches', 'Returns list of patient id ranges', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetPatientBatch'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetPatientBatch', 'Returns list of patient details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/FindAppointmentOpenings'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/FindAppointmentOpenings', 'Returns opening times', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAppointmentStatuses'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAppointmentStatuses', 'Returns list of appointment statuses', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAppointmentTypes'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAppointmentTypes', 'Returns list of appointment types', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetUpdatedAppointments'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetUpdatedAppointments', 'Returns list of appointment details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/CreateAppointment'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/CreateAppointment', 'Creates a patient appointment in the database', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/CreatePatient'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/CreatePatient', 'Create patient', 0, GETDATE())
*/

If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetPractice'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetPractice', 'Returns practice and site details', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetEmployees'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetEmployees', 'Returns Employees', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAudiologists'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAudiologists', 'Returns Employees', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetPatients'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetPatients', 'Returns Patients', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetPatient'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetPatient', 'Returns Patient', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAppointments'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAppointments', 'Returns Appointments', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAppointment'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAppointment', 'Returns Appointment', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetInvoices'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetInvoices', 'Returns Invoices', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetInvoice'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetInvoice', 'Returns Invoice', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetReturns'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetReturns', 'Returns Returns', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetReturn'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetReturn', 'Returns Return', 0, GETDATE())
If(NOT EXISTS(SELECT * FROM ApiUrl where Url='/api/v1/GetAudiograms'))
	insert into ApiUrl (Url, Description, Inactive, DateCreated) values ('/api/v1/GetAudiograms', 'Returns Audiograms', 0, GETDATE())
