using System;
using System.Collections.Generic;
using System.Text;

namespace TIMS_X.Core.Enums
{
    public enum TwilioVoiceEnum
    {
        Man,
        PollyKarl,
        PollyCarla,
        PollyGiorgio,
        PollyMizuki,
        PollyLiv,
        PollyLotte,
        PollyRuben,
        PollyEwa,
        PollyJacek,
        PollyJan,
        PollyMaja,
        PollyDora,
        PollyRicardo,
        PollyCristiano,
        PollyInes,
        PollyCarmen,
        PollyMaxim,
        PollyTatyana,
        PollyAstrid,
        PollyFiliz,
        PollyVicki,
        PollyTakumi,
        PollySeoyeon,
        PollyAditi,
        PollyVitoria,
        PollyMathieu,
        PollyCeline,
        PollyEmma,
        PollyGeraint,
        PollyGwyneth,
        PollyMads,
        PollyNaja,
        PollyHans,
        PollyMarlene,
        PollyNicole,
        PollyRussell,
        PollyAmy,
        PollyBrian,
        PollyChantal,
        Alice,
        PollyRaveena,
        PollyJoanna,
        PollyJoey,
        PollyJustin,
        PollyKendra,
        PollyKimberly,
        PollyMatthew,
        PollySalli,
        PollyConchita,
        PollyEnrique,
        PollyMiguel,
        PollyPenelope,
        PollyIvy,
        Woman
    }
}
