

    export enum PatientRequiredFieldEnum {
        seenBy = 3,
        salutation = 4,
        initial = 6,
        address1 = 8,
        address2 = 9,
        city = 10,
        state = 11,
        zip = 12,
        primaryPhone = 13,
        workPhone = 14,
        workPhoneExt = 15,
        mobilePhone = 16,
        homePhone = 17,
        homePhoneExt = 18,
        dob = 19,
        gender = 20,
        otherPhone = 21,
        otherPhoneExt = 22,
        email = 23,
        ssn = 24,
        alternateContact = 25,
        language = 26,
        alternatePhone = 27,
        race = 28,
        primaryCare = 29,
        ethnicity = 30,
        referringPhysician = 31,
        qbBillTo = 33,
        qbCustomerType = 34,
        county = 35,
        releaseSignature = 36,
        assignmentOfBenefits = 37,
        privacyAgreement = 38,
        consent = 39,
        customText1 = 40,
        customText2 = 41,
        customDate1 = 42,
        customDate2 = 43,
        patientType = 44,
    }